/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Consult: typeof import('./src/components/layout/Consult.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAnchor: typeof import('element-plus/es')['ElAnchor']
    ElAnchorLink: typeof import('element-plus/es')['ElAnchorLink']
    ElStatistic: typeof import('element-plus/es')['ElStatistic']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
